name: a2a-api
services:
- name: api
  github:
    branch: main
    deploy_on_push: true
    repo: your-username/your-repo
  envs:
  - key: PYTHON_VERSION
    value: "3.9"
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: / 